### ISSUE TITLE
UserData/Account Bug

### ISSUE THREAD

**Issue by JarnoLeConte** [hckrs/hckrs.io#104]
The following error showed up in the server console. Possible triggered at time of user registration.

```
Exception in callback of async function: TypeError: Cannot read property 'twitter' of undefined
at packages/account/account/userdata.jsdoc:270:1
at replenish (packages/peerlibrary:async/async/lib/async.js:194:1)
at packages/peerlibrary:async/async/lib/async.js:206:1
at packages/account/account/userdata.jsdoc:274:1
at replenish (packages/peerlibrary:async/async/lib/async.js:194:1)
at packages/peerlibrary:async/async/lib/async.js:206:1
at packages/account/account/userdata.jsdoc:274:1
at replenish (packages/peerlibrary:async/async/lib/async.js:194:1)
at packages/peerlibrary:async/async/lib/async.js:206:1
at packages/account/account/userdata.jsdoc:274:1
```

**Comment by ramshorst** [comment]
It could when I tried connecting trough twitter on my iphone (?)

**Comment by JarnoLeConte** [comment]
This error shows up regularly when an user signs up AND/OR when profile pictures are updated.

Probably related to #137
