### ISSUE TITLE
Attach external login service

### ISSUE THREAD

**Issue by JarnoLeConte** [hckrs/hckrs.io#137]
Error in console at user registration when he/she adds an additional login service.

```
2015-11-20T15:41:41.537322+00:00 app[web.1]: Exception while invoking method 'addServiceToUser' Error: Match error: Expected string, got object
2015-11-20T15:41:41.537326+00:00 app[web.1]:     at checkSubtree (packages/check/match.js:159:1)
2015-11-20T15:41:41.537327+00:00 app[web.1]:     at check (packages/check/match.js:32:1)
2015-11-20T15:41:41.537328+00:00 app[web.1]:     at [object Object].Account.userData.addServiceToCurrentUser (packages/account/account/userdata.jsdoc:124:1)
2015-11-20T15:41:41.537329+00:00 app[web.1]:     at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:160:1)
2015-11-20T15:41:41.537330+00:00 app[web.1]:     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
2015-11-20T15:41:41.537331+00:00 app[web.1]:     at packages/ddp/livedata_server.js:648:1
2015-11-20T15:41:41.537332+00:00 app[web.1]:     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
2015-11-20T15:41:41.537332+00:00 app[web.1]:     at packages/ddp/livedata_server.js:647:1
2015-11-20T15:41:41.537333+00:00 app[web.1]:     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
2015-11-20T15:41:41.537334+00:00 app[web.1]:     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
2015-11-20T15:41:43.300320+00:00 heroku[router]: at=info method=GET path="/_oauth/twitter/?requestTokenAndRedirect=true&state=xxxxxxxx
```

**Comment by JarnoLeConte** [comment]
Probably related to #104
